name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          # Error ko khatam karne ke liye setuptools ka version fix kar rahe hain
          pip install --user --upgrade "setuptools<66.0.0" "buildozer>=1.5.0" "cython<3.0.0" wheel

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Licenses auto-accept
          yes | buildozer android debug --init || true
          
          # Build shuru karne se pehle zaroori checks
          buildozer -v android debug
